---
# aws_sg_loader.yaml - Ben Sampson
# Playbook / Util to load and tag security groups defined in yaml
# See demo.yml for example group examples 
# Expects a region, vpc id and var_file
# e.g ansible-playbook aws_sg_loader.yaml- e"region=us-west-2 vpc_id=vpc-71f8dc14 var_file=ps.yml"
- name: Create AWS Security Groups from config file "{{ var_file }}"
  hosts: localhost
  connection: local
  gather_facts: false
 
  vars:
    - region:
    - vpc_id:
    - var_file:
  
  vars_files:
    - "{{ var_file }}"
  
  tasks:
    - name: Create a Security Group
      register: sg
      ec2_group:
        name: "{{ item.name }}"
        description: "{{ item.description }}"
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules: "{{ item.rules }}"
        rules_egress: "{{ item.rules_egress }}"
      with_items: "{{ security_groups }}"
    
    #- debug: var=sg.results

    # Tag the created groups
    - name: Tag Security Group
      ec2_tag:
        resource: "{{ item.group_id }}"
        region: "{{ item.invocation.module_args.region }}"
        state: present
        tags:
          Name: "{{ item.invocation.module_args.name}}"
      with_items: "{{ sg.results }}"
